var JsonData = 
{
   "types":[
      {
         "type":"news",
         "name":"Zpravy",
         "possibilities":[
            "header",
            "left",
            "right"
         ],
         "settings":[
            "title",
            "content"
         ]
      },      {
         "type":"anket",
         "name":"Anketa do Paticky",
         "possibilities":[
            "footer"
         ],
         "settings":[
            "title",
            "content"
         ]
      },      {
         "type":"news",
         "name":"Zpravy do Leva",
         "possibilities":[
            "left"
         ],
         "settings":[
            "title",
            "content"
         ]
      },
      {
         "type":"text",
         "name":"Volny text",
         "possibilities":[
            "header",
            "left",
            "right"
         ],
         "settings":[
            "title",
            "author",
            "content"
         ]
      },
      {
         "type":"anket",
         "name":"Anketa",
         "possibilities":[
            "footer",
            "left",
            "right"
         ],
         "settings":[
            "title"
         ]
      }
   ],
   "blocks":[
      {
         "name":"Hlavicka",
         "type":"header",
         "size":12,
         "moduls":[
            {
               "type":"text",
               "name":"Logo",
               "possibilities":[
                  "header",
                  "left",
                  "right"
               ],
               "settings":[
                  {
                     "title":"jjj",
                     "content":"tohle je header joo ",
                     "author":"All"
                  }
               ]
            }
         ]
      },
      {
         "name":"Levy sloupec",
           "type":"left",
         "size":6,
         "moduls":[
            {
               "type":"anket",
               "name":"Anketa",
               "possibilities":[
                  "footer",
                  "left",
                  "right"
               ],
               "settings":[
                  {
                     "title":"ahoj",
                     "content":"tohle jj alright",
                     "author":"Ondra"
                  }
               ]
            }
         ]
      },
      {
         "name":"Pravy sloupec",
           "type":"right",
         "size":6,
         "moduls":[
            {
               "type":"news",
               "name":"Zpravy",
               "possibilities":[
                  "header",
                  "left",
                  "right"
               ],
               "settings":[
                  {
                     "title":"Novinky",
                     "content":"To jsou super novinky",
                     "author":"Filip"
                  }
               ]
            },
            {
               "type":"text",
               "name":"Obsah",
               "possibilities":[
                  "header",
                  "left",
                  "right"
               ],
               "settings":[
                  {
                     "title":"loool",
                     "content":"tohle je left Xd",
                     "author":"Filip"
                  }
               ]
            },
            {
               "type":"anket",
               "name":"Vtipna Anketa",
               "possibilities":[
                  "footer",
                  "left",
                  "right"
               ],
               "settings":[
                  {
                     "title":"jjj",
                     "content":"tohle je seeej",
                     "author":"Filip"
                  }
               ]
            }
         ]
      },
      {
         "name":"Patička",
           "type":"footer",
         "size":12,
         "moduls":[
            {
               "type":"text",
               "name":"Text do Prava",
               "possibilities":[
                  "right"
               ],
               "settings":[
                  {
                     "title":"ahoj",
                     "content":"tohle je right",
                     "author":"Ondra"
                  }
               ]
            },
            {
               "type":"anket",
               "name":"Anketa Do paticky",
               "possibilities":[
                  "footer"
               ],
               "settings":[
                  {
                     "title":"ahoj",
                     "content":"tohle je right",
                     "author":"Ondra"
                  }
               ]
            }
         ]
      }
   ]
};
export default JsonData;