var JsonData = 
{
   "types":[
      {
         "type":"news",
         "possibilities":[
            "header",
            "left",
            "right"
         ],
         "settings":[
            "title",
            "content"
         ]
      },
      {
         "type":"text",
         "possibilities":[
            "header",
            "left",
            "right"
         ],
         "settings":[
            "title",
            "author",
            "content"
         ]
      },
      {
         "type":"anket",
         "possibilities":[
            "footer",
            "left",
            "right"
         ],
         "settings":[
            "title"
         ]
      }
   ],
   "blocks":[
      {
         "name":"header",
         "size":12,
         "moduls":[
            {
               "type":"logo je cool",
               "possibilities":[
                  "header",
                  "left",
                  "right"
               ],
               "settings":[
                  {
                     "title":"jjj",
                     "content":"tohle je header joo ",
                     "author":"All"
                  }
               ]
            }
         ]
      },
      {
         "name":"left",
         "size":6,
         "moduls":[
            {
               "type":"anket",
               "possibilities":[
                  "footer",
                  "left",
                  "right"
               ],
               "settings":[
                  {
                     "title":"ahoj",
                     "content":"tohle jj alright",
                     "author":"Ondra"
                  }
               ]
            }
         ]
      },
      {
         "name":"right",
         "size":6,
         "moduls":[
            {
               "type":"news",
               "possibilities":[
                  "header",
                  "left",
                  "right"
               ],
               "settings":[
                  {
                     "title":"Novinky",
                     "content":"To jsou super novinky",
                     "author":"Filip"
                  }
               ]
            },
            {
               "type":"text",
               "possibilities":[
                  "header",
                  "left",
                  "right"
               ],
               "settings":[
                  {
                     "title":"loool",
                     "content":"tohle je left Xd",
                     "author":"Filip"
                  }
               ]
            },
            {
               "type":"anket",
               "possibilities":[
                  "footer",
                  "left",
                  "right"
               ],
               "settings":[
                  {
                     "title":"jjj",
                     "content":"tohle je seeej",
                     "author":"Filip"
                  }
               ]
            }
         ]
      },
      {
         "name":"footer",
         "size":12,
         "moduls":[
            {
               "type":"Right",
               "possibilities":[
                  "left",
                  "right"
               ],
               "settings":[
                  {
                     "title":"ahoj",
                     "content":"tohle je right",
                     "author":"Ondra"
                  }
               ]
            },
            {
               "type":"anket",
               "possibilities":[
                  "footer",
                  "left",
                  "right"
               ],
               "settings":[
                  {
                     "title":"ahoj",
                     "content":"tohle je right",
                     "author":"Ondra"
                  }
               ]
            }
         ]
      }
   ]
};
export default JsonData;